### ISSUE TITLE
Coq 8.13 release?

### ISSUE THREAD

**Issue by anton-trunov** [damien-pous/relation-algebra#16]
Hi, the optional deps have recently gained support for Coq 8.13 (e.g. for `aac-tactics` --  https://github.com/coq/opam-coq-archive/pull/1526) and the current `master` branch seems to compile fine with Coq 8.13 too. It would be great to have a new release! Thanks in advance.

**Comment by damien-pous** [comment]
Hi @anton-trunov , I've just released relation-algebra.1.7.5.
It should arrive in opam soon, apparently in extra-dev only for now (waiting for coq 8.13 to be released via opam if I understand correctly)

**Comment by anton-trunov** [comment]
Thanks so much @damien-pous!
