### ISSUE TITLE
dev version of relation-algebra compatible with coq.dev

### ISSUE THREAD

**Issue by anton-trunov** [damien-pous/relation-algebra#17]
Since `relation-algebra` is in [Coq's CI](https://github.com/coq/coq/blob/810e91530071159e27e89bf0ca6bc36c8bb1d034/Makefile.ci#L54), would you mind including a `dev` version tracking its `master` branch to `coq-extra-dev` opam repo? This would make it easier to include `relation-algebra` as a dependency into a CI for projects aiming to stay compatible with Coq's dev version and relying on `relation-algebra` package.

By the way, I'm happy to give you a hand with this if you think this is something worth doing. Thank you in advance!

**Comment by damien-pous** [comment]
Hi @anton-trunov,

Just to be sure: you mean having an opam package coq-relation-algebra.dev in extra-dev, whose url would be 
https://github.com/damien-pous/relation-algebra/archive/master.zip
?
I can do that, but what should I use as checksum?
Also, what version constraints should I impose about coq in the opam file? 

Best,
Damien

**Comment by anton-trunov** [comment]
Hi @damien-pous! Indeed, that's what I meant. Thank you for handling this. 

> I can do that, but what should I use as checksum?

You can leave out  a checksum in this case.

> Also, what version constraints should I impose about coq in the opam file?

I'd be happy with `coq.dev`. Maybe we could go for `dev`-only and tweak it if there is need in the future.

**Comment by damien-pous** [comment]
Should be done now ; please let me know if something went wrong!

**Comment by anton-trunov** [comment]
It works like a charm! Thanks again.
