### ISSUE TITLE
Coq 8.14 compatibility release?

### ISSUE THREAD

**Issue by anton-trunov** [damien-pous/relation-algebra#24]
Hi, looks like the deps have Coq 8.14 support. Are there any plans to make a Coq 8.14 compatibility release? Thanks in advance!

**Comment by damien-pous** [comment]
Hi @anton-trunov, yes, I'll do one! 
Possibly only next week, though...

**Comment by damien-pous** [comment]
Done and submitted to opam-coq-archive!

**Comment by anton-trunov** [comment]
Great! Thanks a bunch
