### ISSUE TITLE
Please create a tag for Coq 8.16 in Coq Platform 2022.09

### ISSUE THREAD

**Issue by MSoegtropIMC** [damien-pous/relation-algebra#35]
The Coq team released Coq `8.16+rc1` on June 01, 2022.
The corresponding Coq Platform release `2022.09` should be released before **September 15, 2022**.
It can be delayed in case of difficulties until October 15, 2022, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (preview) **does not work** with Coq `8.16+rc1`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI is currently testing commit 00f84a00321ed87e84a723c34e177a59ccd8e230 on repository https://github.com/damien-pous/relation-algebra - which likely means that this commit does work in Coq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.16, **preferably before August 31, 2022**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before August 17, 2022, it will be included in an early Coq Platform beta release of the for Coq 8.16+rc1.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.16+rc1~2022.09~preview1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.16~2022.09~preview1.sh) which already supports Coq version `8.16+rc1` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/274

**Comment by MSoegtropIMC** [comment]
@damien-pous : can you please inform us about your release plans? As far as I can tell the latest 1.7.7 does not work with Coq 8.16, but e.g. commit (00f84a00321ed87e84a723c34e177a59ccd8e230) does work.

I am only 3/4 through the list, but so far this is the only package in Coq Platform "full" without a release for 8.16. For a beta using a preview package pinned to the above commit, but I need a release soon.

**Comment by damien-pous** [comment]
Hi @MSoegtropIMC,
Sorry for the delay, for some reason I didn't receive any email notification when you opened the issue one month ago, so that it went completely unnoticed from my side.
I'll have a look by the end of the week, hopefully I'll come up with a 8.16 version by then!

**Comment by MSoegtropIMC** [comment]
@damien-pous : This seems to be a common issue. I will create a list of people to "at" notify for each project in Coq Platform and include an "at" notification in the future to avoid putting unnecessary time pressure on people.

Since Coq 8.16.0 was delayed, I will do the beta around September 15th and the release 2 weeks later. For the beta it would be OK to go with a pinned version, but I would appreciate a not from you which commit I should use. Currently I am using [opam](https://github.com/coq/platform/blob/main/opam/opam-coq-archive/released/packages/coq-relation-algebra/coq-relation-algebra.preview/opam). Of course a final release Friday or Monday would be perfect.

**Comment by damien-pous** [comment]
@MSoegtropIMC: just released a v.1.7.8 for Coq 8.16, and submitted the corresponding package to opam-coq-archive.
Leaving the issue open as requested.

**Comment by MSoegtropIMC** [comment]
Thanks! I updated relation algebra to version 1.7.8 in the preparation branch and close this issue.
