### ISSUE TITLE
Please create a tag for Coq 8.18 in Coq Platform 2023.10

### ISSUE THREAD

**Issue by rtetley** [damien-pous/relation-algebra#40]
The Coq team released Coq `8.18.0` on September 7th, 2023.
The corresponding Coq Platform release `2023.10` should be released before **November 30th, 2023**.
It can be delayed in case of difficulties until January 15th, 2023, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (1.7.9) **does not work** with Coq `8.18.0`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI is currently testing commit 1c37f34e53a0a0c523fbd813f9ae10e18f6e41f2 on repository https://github.com/damien-pous/relation-algebra - which likely means that this commit does work in Coq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.18, **preferably before October 31st, 2023**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before October 31st, 2023, it will be included in an early Coq Platform beta release of the for Coq 8.18.0.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.18+beta1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.18+beta1.sh) which already supports Coq version `8.18.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/372

**Comment by SnarkBoojum** [comment]
I could get version 1.7.9 to compile with just:
```
--- coq-relation-algebra.orig/src/fold.ml
+++ coq-relation-algebra/src/fold.ml
@@ -26,7 +26,7 @@
   let obt = Monoid.ob ops in
   (* TOTKINK: Use  Evarconv.conv ? *)
   let unifiable sg env x y =
-    try sigma := Unification.w_unify env sg Reduction.CONV x y; true
+    try sigma := Unification.w_unify env sg Conversion.CONV x y; true
     with _ -> false
   in
```

**Comment by damien-pous** [comment]
Hi,
Thanks for the help, this message just to reassure you that I'm on it: should be able to double check everything this Friday.
Damien

**Comment by damien-pous** [comment]
Hi @rtetley 
just released/tagged v1.7.10, which compiles with Coq8.18
Is it fine with you?
(I'll propagate the package to opam then)
Damien

**Comment by rtetley** [comment]
Works fine ! Will close the issue once [this](https://github.com/coq/platform/pull/379) is merged. 
Let me know once you've propagated to opam! 
Cheers !

**Comment by damien-pous** [comment]
Done, in opam!
